name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  shortenertest:
    runs-on: ubuntu-latest
    container: golang:1.17

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install deps
        run: |
          apt-get update && apt-get install -y --no-install-recommends lsof

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download shortenertest binary
        uses: robinraju/release-downloader@v1
        with:
          repository: Yandex-Practicum/go-autotests-bin
          latest: true
          fileName: shortenertest
          out-file-path: .tools

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/shortenertest
          mv $GITHUB_WORKSPACE/.tools/shortenertest /usr/local/bin/shortenertest

      - name: Start web server
        run: |
          go run ./cmd/shortener/... &
          timeout 10 sh -c 'until lsof -i:8080; do sleep 1s; done'
        env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: redis

      - name: "[Code increment #1] Check basic handlers"
        if: always()
        run: |
          shortenertest -test.v -test.run=^TestBasicHandlers$ ./...

      - name: "[Code increment #2] Check handlers unit tests"
        if: always()
        run: |
          shortenertest -test.v -test.run=^TestHandlersCovered$ ./...

      - name: "[Code increment #3] Check HTTP framework usage"
        if: always()
        run: |
          shortenertest -test.v -test.run=^TestUsesHTTPFramework$ ./...

      - name: "Code increment #4"
        if: always()
        run: |
          shortenertest -test.v -test.run=^TestIteration4$ -source-path=. -binary-path=cmd/shortener/shortener

      - name: "Code increment #5"
        if: always()
        run: |
          SERVER_HOST=$(random domain)
          SERVER_PORT=$(random unused-port)
          shortenertest -test.v -test.run=^TestIteration5$ \
              -binary-path=cmd/shortener/shortener \
              -server-host=$SERVER_HOST \
              -server-port=$SERVER_PORT \
              -server-base-url="http://$SERVER_HOST:$SERVER_PORT"

      - name: "Code increment #6"
        if: always()
        run: |
          SERVER_PORT=$(random unused-port)
          TEMP_FILE=$(random tempfile)
          shortenertest -test.v -test.run=^TestIteration6$ \
              -binary-path=cmd/shortener/shortener \
              -server-port=$SERVER_PORT \
              -file-storage-path=$TEMP_FILE

      - name: "Code increment #7"
        if: always()
        run: |
          SERVER_PORT=$(random unused-port)
          TEMP_FILE=$(random tempfile)
          shortenertest -test.v -test.run=^TestIteration7$ \
              -binary-path=cmd/shortener/shortener \
              -server-port=$SERVER_PORT \
              -file-storage-path=$TEMP_FILE

      - name: "Code increment #8"
        if: always()
        run: |
          shortenertest -test.v -test.run=^TestIteration8$ -source-path=. -binary-path=cmd/shortener/shortener
